import { useState } from 'react';
import { Popover, PopoverContent, PopoverTrigger } from './ui/popover';
import { Icon, fieldClass } from './token-controls';
type FontName = { family: string; style: string };
type Props = { label: string; value: string; disabled?: boolean; fonts: FontName[]; fontError: string; fontsLoading: boolean; onRetryFonts: () => void; onChange: (family: string) => void };
export function FontPicker({label,value,disabled,fonts,fontError,fontsLoading,onRetryFonts,onChange}: Props) {
  const [open,setOpen]=useState(false), [query,setQuery]=useState('');
  const families=[...new Set(fonts.map(f=>f.family))].sort((a,b)=>a.localeCompare(b)).filter(f=>f.toLowerCase().includes(query.toLowerCase()));
  const select=(family:string)=>{onChange(family);setOpen(false);};
  return <div><label className="mb-1 block text-sm font-medium text-muted-foreground">{label}</label><Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button disabled={disabled} aria-label={label} className={`${fieldClass} justify-between`}><Icon name="text_fields" className="text-accent"/><span className="min-w-0 flex-1 truncate text-left" title={value}>{value}</span><Icon name="expand_more"/></button></PopoverTrigger><PopoverContent align="start" className="w-[320px] max-w-[calc(100vw-16px)] p-0" collisionPadding={8}><input autoFocus aria-label={`Search ${label}`} placeholder="Search fonts by name…" value={query} onChange={e=>setQuery(e.target.value)} className="h-[50px] w-full border-b border-border bg-card px-4 outline-none"/><div className="max-h-[300px] overflow-y-auto">{families.map(name=><button key={name} onClick={()=>select(name)} className={`flex min-h-[60px] w-full flex-col items-start gap-1 border-b border-border px-4 py-3 text-left ${name===value?'bg-accent text-white':'hover:bg-secondary'}`}><span className="text-sm">{name}</span><span className="text-xs" style={{fontFamily:name}}>The quick brown fox jumps</span></button>)}{!families.length&&<p role="status" className="p-4 text-sm">{fontsLoading?'Loading Figma fonts…':fonts.length?'No fonts found.':'No fonts available.'}</p>}</div>{fontError&&<p role="alert" className="p-3 text-sm text-destructive">{fontError}</p>}{!fontsLoading&&(!fonts.length||fontError)&&<button onClick={onRetryFonts} className="p-3 text-sm text-accent">Retry loading fonts</button>}</PopoverContent></Popover></div>;
}
